namespace FFImageLoading.Helpers.Exif
{
	public enum ExifOrientation
	{
		ORIENTATION_UNDEFINED = 0,
		ORIENTATION_NORMAL = 1,
		ORIENTATION_FLIP_HORIZONTAL = 2,
		ORIENTATION_ROTATE_180 = 3,
		ORIENTATION_FLIP_VERTICAL = 4,
		ORIENTATION_TRANSPOSE = 5,
		ORIENTATION_ROTATE_90 = 6,
		ORIENTATION_TRANSVERSE = 7,
		ORIENTATION_ROTATE_270 = 8,
	}
}
