// <autogenerated />
            using System;
            using System.Reflection;
            [assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETStandard,Version=v1.0", FrameworkDisplayName = ".NETStandard,Version=v1.0")]
